version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_ai_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    networks:
      - backend # Menghubungkan bot langsung ke jaringan bersama

networks:
  backend:
    external: true # Memberitahu Docker untuk memakai network 'backend' yang sudah ada
